Newspaper/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('arobic/', include('arobic.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

arobic/urls.py
from django.urls import path

from . import views
from .views import arLatestPostt,arMeoPostt



app_name = 'arobic'

urlpatterns = [
path('', views.arindex, name='arindex'),
path('ar/post/<int:pk>/', arLatestPostt.as_view(), name='arlatestpost'),

path('ar/meo/<int:pk>/', arMeoPostt.as_view(), name='armeo'),
path('ar/gas/', views.arGas, name='argas'),
path('ar/cripto/', views.arCripto, name='arcripto'),
path('ar/enorgy/', views.arEnorgy, name='arenorgy'),
path('ar/meo/', views.arMEO, name='armeo'),
path('ar/tech/', views.arTech, name='artech'),

]

base/urls.py
from django.urls import path

from . import views
from .views import LatestPostt,MeoPostt

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', LatestPostt.as_view(), name='latestpost'),

    path('meo/<int:pk>/', MeoPostt.as_view(), name='meo'),
    path('gas/', views.Gas, name='gas'),
    path('cripto/', views.Cripto, name='cripto'),
    path('enorgy/', views.Enorgy, name='enorgy'),
    path('meo/', views.MEO, name='meo'),
    path('tech/', views.Tech, name='tech'),



    ]

base/models.py
from django.db import models
from django.utils import timezone
from embed_video.fields import EmbedVideoField
from multiselectfield import MultiSelectField


# Create your models here.


class LatestPost(models.Model):
    MY_CHOICES = ((1, 'Gas&Oil'),
              (2, 'Economy'),
              (3, 'Energy'),
              (5, 'Technology'))
    title = models.CharField(max_length=100)
    content = models.TextField()
    post_pic = models.ImageField(default='welcome.gif',null=True,blank=True)
    category = MultiSelectField(choices=MY_CHOICES,
                         max_choices=4,
                         max_length=30,null=True,blank=True)
    date_posted = models.DateTimeField(default=timezone.now)



    def __str__(self):
        return self.title







class MEOCHANNEL(models.Model):

    title = models.CharField(max_length=100)
    video = EmbedVideoField(blank=True)
    date_posted = models.DateTimeField(default=timezone.now)



    def __str__(self):
        return self.title

base/views.py
from django.shortcuts import render,redirect
from . models import *
from django.views.generic import  DetailView
from django.utils import timezone

# Create your views here.

def index(request):
    l=LatestPost.objects.all().order_by('-date_posted')[:1]
    ll=LatestPost.objects.all().order_by('-date_posted')[1:2]
    lll=LatestPost.objects.all().order_by('date_posted').reverse()[1:3]
    posts=LatestPost.objects.all().order_by('date_posted').reverse()[3:7]
    bb=LatestPost.objects.all().order_by('-date_posted')[:5]
    if request.method == 'GET':
        category=['1']
        gass=LatestPost.objects.order_by('-date_posted').filter(category=category)[:2]

    try:
        if request.method =='GET':
            category=['2']
            p=LatestPost.objects.order_by('-date_posted').filter(category=category)[:2]
    except:
        pass

    try:
        if request.method =='GET':
            category=['3']
            c=LatestPost.objects.order_by('-date_posted').filter(category=category)[:2]
    except:
        pass

    try:
        if request.method =='GET':
            category=['4']
            d=LatestPost.objects.order_by('-date_posted').filter(category=category)[:2]
    except:
        pass


    try:
        if request.method =='GET':
            category=['5']
            e=LatestPost.objects.order_by('-date_posted').filter(category=category)[:2]
    except:
        pass

    try:
        if request.method =='GET':
            video=MEOCHANNEL.objects.all().order_by('-date_posted')[:2]
    except:
        pass



    context={'gass':gass,'p':p,'c':c,'d':d,'e':e,'video':video,'posts':posts,'l':l,'ll':ll,'bb':bb,'lll':lll}
    return render(request, 'base/index.html',context)


def Gas(request):
    category=['1']
    gass=LatestPost.objects.order_by('-date_posted').filter(category=category)
    video=MEOCHANNEL.objects.all().order_by('-date_posted')[:1]

    context={'gass':gass,'video':video}
    return render(request, 'base/gas.html',context)


def MEO(request):
    gass=MEOCHANNEL.objects.all().order_by('-date_posted')
    video=MEOCHANNEL.objects.all().order_by('-date_posted')[:1]

    context={'gass':gass,'video':video}
    return render(request, 'base/meo.html',context)


def Cripto(request):
    category=['2']
    gass=LatestPost.objects.order_by('-date_posted').filter(category=category)
    video=MEOCHANNEL.objects.all().order_by('-date_posted')[:1]

    context={'gass':gass,'video':video}
    return render(request, 'base/economy.html',context)


def Enorgy(request):
    category=['3']
    gass=LatestPost.objects.order_by('-date_posted').filter(category=category)
    video=MEOCHANNEL.objects.all().order_by('-date_posted')[:1]

    context={'gass':gass,'video':video}
    return render(request, 'base/enorgy.html',context)


def Tech(request):
    category=['5']
    gass=LatestPost.objects.order_by('-date_posted').filter(category=category)
    video=MEOCHANNEL.objects.all().order_by('-date_posted')[:1]

    context={'gass':gass,'video':video}
    return render(request, 'base/tech.html',context)

class LatestPostt(DetailView):
    model = LatestPost










class MeoPostt(DetailView):
    model = MEOCHANNEL

base/templates/base/economy.html
{%load static%}
{% load embed_video_tags %}
<!DOCTYPE html>
<html lang="en-US">
<head>
	<title>Middle East Oil</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<!-- Seo Meta -->
		<meta name="description" content="iPress - Responsive News/Blog/Magazine HTML5 Template">
		<meta name="keywords" content="iPress, magazine, light, dark, themeforest, multi purpose, premium, unlimited, blog, news, AD, optimized">

	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles/icons.css'%}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles/animate.css'%}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles/responsive.css'%}" media="screen" />
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>

	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">
	<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png'%}">

	<!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=EmulateIE8; IE=EDGE" />
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div id="layout" class="boxed">
		<header id="header">
			<div class="a_head">
				<div class="row clearfix">
					<div class="breaking_news lefter">
						<div class="freq_out">
							<div class="freq"><div class="inner_f"></div><div id="layerBall"></div></div>
						</div><!-- /freq -->
						<ul id="js-news" class="js-hidden">

						</ul><!-- /js news -->
					</div><!-- /breaking news -->

					<div class="right_bar">
						<div class="lang">

						</div><!-- /lang -->

						<div class="social social_head">
							<a href="www.facebook.com/middleeastoil.net" class="bottomtip" title="Facebook"><i class="fa-facebook"></i></a>
							<a  href="https://www.youtube.com/channel/UCg6PYIAN4wTuuhNn_y4yMvQ" class="bottomtip" title="Linkedin"><i class="fa-youtube"></i></a>
              	<a href="https://twitter.com/middleeastoil"  class="bottomtip" title="Twitter"><i class="fa-twitter"></i></a>
							<a href="www.rss.com" class="bottomtip" title="Google Plus"><i class="fa-rss"></i></a>
						</div><!-- /social -->

						<span id="date_time"></span><!-- /date -->
					</div><!-- /right bar -->
				</div><!-- /row -->
			</div><!-- /a head -->

			<div class="b_head">
				<div class="row clearfix">
					<div class="logo">
						<a href="index.html" title=""><img src="images/logo.png" alt=""></a>
					</div><!-- /logo -->


				</div><!-- /row -->
			</div><!-- /b head -->


						<div class="b_head">
							<div class="row clearfix">
								<div class="logo">
									<a href="{% url 'index' %}" title=""><img src="{% static 'images/logo.png'%}" alt=""></a>
								</div><!-- /logo -->


							</div><!-- /row -->
						</div><!-- /b head -->

						<div class="row clearfix">
							<div class="sticky_true">
								<div class="c_head clearfix">
									<nav>
										<ul class="sf-menu">
											<li class="current colordefault home_class"><a href="{% url 'index'%}"><i class="icon-home"></i></a>

											</li>

											<li class="color2"><a href="{% url 'gas'%}">GAS&OIL</a>
												<ul class="col4 mega">

												</ul>
											</li>
											<li class="color3"><a href="{% url 'cripto'%}">ECONOMY </a>
												<ul class="col4 mega">

												</ul>
											</li>
											<li class="color4"><a href="{% url 'enorgy'%}">ENERGY </a>
												<ul class="col4 mega">


												</ul>
											</li>

											<li class="color6"><a href="{% url 'tech'%}">Technology</a></li>

											<li class="color6"><a href="{% url 'meo'%}">MEO Channel </a></li>

												<li class="color6"><a href="{% url 'arobic:arindex' %}">EN/AR </a></li>

										</ul><!-- /menu -->

									</nav><!-- /nav -->

									<div class="right_icons">
										<a class="random_post bottomtip" href="www.facebook.com/middleeastoil.net" title=""><i class="fa fa-facebook"></i></a>
											<a class="random_post bottomtip" href="https://www.youtube.com/channel/UCg6PYIAN4wTuuhNn_y4yMvQ" title=""><i class="fa fa-youtube"></i></a>
												<a class="random_post bottomtip" href="https://twitter.com/middleeastoil" title=""><i class="fa fa-twitter"></i></a>
													<a class="random_post bottomtip" href="www.rss.com" title=""><i class="fa fa-rss"></i></a>
									<div class="search">

									<div class="s_form">

									</div>
									</div>
									</div>
									</div>
									</div>
									</div>
									</header>

		<div class="page-content">
			<div class="row clearfix">
				<div class="grid_9 alpha">
					<div class="grid_8 alpha posts">
						<div class="title colordefault"><h4> ECONOMY </h4></div>

					<!-- post -->
						{% for post in gass %}
						<div class="post_day mbf clearfix">
							<div class="grid_6 alpha relative">
								<a class="float-shadow" href="{% url 'latestpost' post.id %}"><img style="width:300px;height:170px;" src="{{post.post_pic.url}}" alt=""></a>
							</div><!-- /grid6 alpha -->
							<div class="grid_6 omega">
								<div class="post_day_content">
									<h3> <a href="{% url 'latestpost' post.id %}">{{post.title}}</a> </h3>
									<div class="meta mb"> {{post.date_posted| date:"F d Y"}}   <a href="{% url 'latestpost' post.id %}"></a> </div>
									<p> {{ post.content|safe|truncatewords_html:9 }} </p>
								</div><!-- /post content -->
							</div><!-- /grid6 omega -->

						</div><!-- /post day -->
							{% endfor %}
					<!-- /post -->




					<div class="pagination-tt clearfix">
						<ul>
							<li><span>1</span></li>
							<li><a href="#">2</a></li>

						</ul>

					</div><!-- /pagination -->

					</div><!-- end grid9 -->

					<div class="grid_4 omega sidebar sidebar_b">
						<div class="widget">
							<div class="title"><h4>New Video</h4></div>
							{% for post in video %}
							{% video post.video '100% x 50%' %}
							 {% endfor %}
						 	</div><!-- widget -->

						<div class="widget">
							<div class="title"><h4>twitter</h4></div>
						<a class="twitter-timeline" data-height="300" href="https://twitter.com/middleeastoil?ref_src=twsrc%5Etfw">Tweets by middleeastoil</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

						</div><!-- widget -->

						<div class="widget">





						</div><!-- widget -->

						<div class="widget">


						</div><!-- widget -->

					</div><!-- end grid9 -->
				</div><!-- end grid9 -->

				<div class="grid_3 omega sidebar sidebar_a">


					<div class="widget">
						<div class="ads_widget clearfix">
							<a href="#"><img src="images/ads2.jpg" alt="#"></a>
							<a href="#" class="lefter mt"><img src="images/ads3.jpg" alt="#"></a>
							<a href="#" class="righter mt"><img src="images/ads3.jpg" alt="#"></a>
						</div><!-- widget -->
					</div><!-- widget -->

					<div class="widget">


							<div class="small_slider_hots owl-carousel owl-theme">
								<div class="item clearfix">

								</div>
								<div class="item clearfix">

								</div>
							</div><!-- /slides -->
					</div><!-- /widget -->

					<div class="widget">
						<div class="latest_tweets">

						</div><!-- /latest tweets -->
					</div><!-- /widget -->

					<div class="widget">
						<div class="title"><h4>MiddleEastOil Stocks</h4></div>
					</div>
					<script type="text/javascript" src="https://www.oil-price.net/COMMODITIES/gen.php?lang=en"> </script>
					<noscript> To get <a href="http://www.oil-price.net/dashboard.php?lang=en#COMMODITIES">gold, oil and
						commodity prices</a>, please enable Javascript.</noscript>

								<br><br><br><br>
						<div class="">
							<script type="text/javascript" src="https://www.oil-price.net/widgets/brent_crude_price_large/gen.php?lang=en"> </script>
							<noscript> To get the BRENT <a href="http://www.oil-price.net/dashboard.php?lang=en#brent_crude_price_large">oil price</a>,
								 please enable Javascript.</noscript>

						</div>

					</div><!-- /widget -->

				</div><!-- /grid3 sidebar A -->
			</div><!-- /row -->
		</div><!-- /end page content -->

		<footer id="footer">
			<div class="row clearfix">
				<div class="grid_3">
					<div class="widget">
						<div class="title"><h4>About MiddleEastOil</h4></div>
						<p> iPress is a magazine/blog/ad/review template. Nunc montes odio phasellus dignissim, aenean, nec augue velit integer elementum ut montes quis integer cursus, est purus, lectus duis, scelerisque tincidunt ultricies phasellus elementum turpis tristique.<br><br>

Email:	<a href="contact.html">MiddleEastOil@gmail.com</a> </p>
					</div><!-- /widget -->
				</div><!-- /grid3 -->

				<div class="grid_3">
					<div class="widget">
						<div class="title"><h4>Recent Posts</h4></div>

					</div><!-- /widget -->
				</div><!-- /grid3 -->

				<div class="grid_3">
					<div class="widget">
						<div class="title"><h4>Best Reviews</h4></div>

					</div><!-- /widget -->
				</div><!-- /grid3 -->

				<div class="grid_3">
					<div class="widget">
						<div class="title"><h4>Newsletters</h4></div>
						<p> To receive the latest updates and Latest Posts enter your email. </p>
						<form id="newsletters" method="post" action="" target="popupwindow" onsubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=sevenpsd', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">
							<input type="email" onfocus="if (this.value=='Type Your Email') this.value = '';" onblur="if (this.value=='') this.value = 'Type Your Email';" value="Type Your Email" placeholder="Type Your Email" required="required">
							<button type="submit"><i class="icon-checkmark"></i></button>
						</form>
					</div><!-- /widget -->

					<div class="widget">
						<div class="title"><h4>Follow us</h4></div>
						<div class="social">
							<a href="#" class="toptip" title="Twitter"><i class="fa-twitter"></i></a>
							<a href="#" class="toptip" title="Facebook"><i class="fa-facebook"></i></a>
							<a href="#" class="toptip" title="Google Plus"><i class="fa-google-plus"></i></a>
							<a href="#" class="toptip" title="Linkedin"><i class="fa-linkedin"></i></a>
							<a href="#" class="toptip" title="Github"><i class="fa-github"></i></a>
							<a href="#" class="toptip" title="instagram"><i class="fa-instagram"></i></a>
							<a href="#" class="toptip" title="Dribbble"><i class="fa-dribbble"></i></a>
						</div><!-- /social -->
					</div><!-- /widget -->
				</div><!-- /grid3 -->

			</div><!-- /row -->

			<div class="row clearfix">
				<div class="footer_last">
					<span class="copyright">© 2020 <a href=""></a>. All Rights Reserved. Powered by <a href="">Middle East Oil</a>.</span>

					<div id="toTop" class="toptip" title="Back to Top"><i class="icon-arrow-thin-up"></i></div>
				</div><!-- /last footer -->
			</div><!-- /row -->

		</footer><!-- /footer -->

	</div><!-- /layout -->

	<!-- Scripts -->
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/ipress.js"></script>
		<script type="text/javascript" src="js/owl.carousel.min.js"></script>
		<script type="text/javascript" src="js/jquery.ticker.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
		<script type="text/javascript">
		/* <![CDATA[ */
			function date_time(id){
				date = new Date;
				year = date.getFullYear();
				month = date.getMonth();
				months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'Jully', 'August', 'September', 'October', 'November', 'December');
				d = date.getDate();
				day = date.getDay();
				days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
				h = date.getHours();
				if(h<10){
					h = "0"+h;}
					m = date.getMinutes();
					if(m<10){
						m = "0"+m;
					}
					s = date.getSeconds();
					if(s<10){
						s = "0"+s;
					}
				// result = ''+days[day]+' '+months[month]+' '+d+' '+year+' '+h+':'+m+':'+s;
				result = ''+days[day]+' '+d+' '+months[month]+' '+year;
				document.getElementById(id).innerHTML = result;
				setTimeout('date_time("'+id+'");','1000');
				return true;
			}
			window.onload = date_time('date_time');
		/* ]]> */
		</script>
		<script src="{% static 'node9/js/js_PNwjDNkjBk5p-bNp6h2tUNtBAuT2CZ0HmC4WevZInmw.js'%}"></script>
</body>
</html>